name: ptcgsim

services:

  app:
    image: ptcgsim-app
    build:
      context: ..
      dockerfile: ./docker/web/Dockerfile
    user: node
    working_dir: /app/server
    environment:
      NODE_ENV: production
    expose:
      - 4000
    ports:
      - 4000:4000 
    volumes:
      - ../server/database/:/app/server/database

  api:
    image: ptcgsim-api
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile
    working_dir: /app
    expose:
      - 8000
    ports:
      - 8000:8000 

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432 
    ports:
      - 5432:5432 

  storybook:
    image: ptcgsim-storybook
    build:
      context: ..
      dockerfile: ./docker/storybook/Dockerfile
    expose:
      - 80
    ports:
      - 8080:80 

volumes:
  postgres-data:
