# name: ptcg-sim

services:

  ptcgweb:
    image: web
    build:
      context: ..
      dockerfile: ./docker/web/Dockerfile
    user: node
    working_dir: /app/server
    environment:
      NODE_ENV: production
    expose:
      - 4000
    ports:
      - 4000:4000 
    volumes:
      - ../server/database/:/app/server/database

  storybook:
    image: storybook
    build:
      context: ..
      dockerfile: ./docker/storybook/Dockerfile
    expose:
      - 80
    ports:
      - 8080:80 
